[package]
name = "codius-sandbox-core"
version = "0.0.1"
authors = ["Torrie Fischer <torrie@ripple.com>"]

[dependencies.rust-seccomp]
git = "https://github.com/tdfischer/rust-seccomp"

[lib]
name = "codius-sandbox-core"
crate_type = ["staticlib"]
