[package]
name = "codius-sandbox-core"
version = "0.0.1"
authors = ["Torrie Fischer <torrie@ripple.com>"]

[dependencies.seccomp]
git = "git://github.com/codius/rust-seccomp"

[dependencies.ptrace]
git = "git://github.com/codius/rust-ptrace"

[lib]
name = "codius-sandbox-core"
